### ISSUE TITLE
头像css优化建议

### ISSUE THREAD

**Issue by 317482454** [HeadingMobile/fabu.love#10]
获得光标事件头像出现1px的位移
![image](https://user-images.githubusercontent.com/16585053/44894619-46516480-ad23-11e8-8422-de1b3adcd6e0.png)
添加默认边框占位
 .headernav-wrapper .rightWrapper .userwrapper {
    display: inline-block;
    height: 100%;
    border-top: solid 1px #fff;
    border-left: solid 1px #fff;
    border-right: solid 1px #fff;
  }

**Comment by 317482454** [comment]
代码重复
https://github.com/HeadingMobile/fabu.love/blob/master/client/src/components/main/mainNav.vue

![image](https://user-images.githubusercontent.com/16585053/44897109-2030c200-ad2d-11e8-9a3b-34fdf6e37183.png)

**Comment by Darren-chenchen** [comment]
#14 已修复头像问题和代码重复问题，谢谢 #
