### ISSUE TITLE
做得非常好的项目,有几点疑问????

### ISSUE THREAD

**Issue by luckydzp** [HeadingMobile/fabu.love#15]
1. 应用详情页显示的下载地址需要token才能访问?这个地址的意义是什么?
2. 应用编辑里显示到下载页是什么意思,有什么作用
3. 发布版本后,点击预览,希望下方可以显示历史版本,点击可以切换历史版本,这个非常重要
4. 希望增加版本升级日志

**Comment by zakiso** [comment]
1.详情里的下载地址不需要token就可以访问
2.编辑里的显示到下载页,其实就是用来显示历史版本用的,不过这个功能还没做好
3.你这种方式好像更好,就是如果有token来请求详情页的时候, 可以编辑历史版本的状态,是否显示,(本来我是做到编辑里面的)
4.这个可以考虑增加,谢谢反馈
