### ISSUE TITLE
你好，所有流程走完，登录页面也正常，就是注册接口老是失败。是什么情况呢

### ISSUE THREAD

**Issue by we11cheng** [HeadingMobile/fabu.love#18]
![wechatimg3](https://user-images.githubusercontent.com/13333981/45348017-0ff7cd00-b5e0-11e8-8439-205d334a926b.jpeg)

**Comment by zakiso** [comment]
麻烦贴一下完整的信息, request 和response的

**Comment by we11cheng** [comment]
http://47.98.177.125:3010/login 这是我搭建的。
<img width="877" alt="wx20180911-165517 2x" src="https://user-images.githubusercontent.com/13333981/45349346-9c57bf00-b5e3-11e8-9581-607fe53c9c5b.png">

**Comment by zakiso** [comment]
你请求的地址是你本地地址,

**Comment by we11cheng** [comment]
方不方便加个微信或者qq。我把config.js 和nginx 配置发你一下。

**Comment by we11cheng** [comment]
其他我没改过

**Comment by we11cheng** [comment]
![qq20180911-173033](https://user-images.githubusercontent.com/13333981/45351317-754fbc00-b5e8-11e8-8c62-358f3a5ebb69.png)
![wx20180911-172520](https://user-images.githubusercontent.com/13333981/45351319-75e85280-b5e8-11e8-91ce-1b6ef1c6498a.png)

**Comment by zakiso** [comment]
邮件我, 我邮件给你我的联系方式

**Comment by we11cheng** [comment]
已解决。
