### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by yzbwork** [HeadingMobile/fabu.love#20]
你好，是否有管理员账号，如果关闭用户注册之后，怎么添加用户，ths

**Comment by yzbwork** [comment]
![image](https://user-images.githubusercontent.com/29591778/45477218-a0b2e200-b773-11e8-8bbf-c45495807e4c.png)
版本编辑的时候，不能滑动，下面的确定和取消按钮被遮挡

**Comment by yzbwork** [comment]
这里的显示到下载页，关闭和打开似乎没有什么变化

**Comment by zakiso** [comment]
admin功能和显示到下载页 等待开发中. 
判断版本号 Android是通过versionCode 进行判断的iOS判断的是CFBundleVersion , 就是build号. 建议使用苹果的agvtool管理, 使用git的提交次数作为 build号. 参考https://developer.apple.com/library/archive/qa/qa1827/_index.html

**Comment by yzbwork** [comment]
好的，谢谢
