### ISSUE TITLE
部分安卓和苹果APP的名字无法获取到,上传fir都能识别出来

### ISSUE THREAD

**Issue by WhoJave** [HeadingMobile/fabu.love#25]

**Comment by zakiso** [comment]
能否提供一下 ipa和apk包

**Comment by WhoJave** [comment]
@zakiso  改好 
苹果的这样就可以 不是所有的默认都配了displayName的 
`info.appName = data.metadata.CFBundleDisplayName ? data.metadata.CFBundleDisplayName : data.metadata.CFBundleName`
安卓的改成这样 将 > 2修改为>1 去掉em 
![image](https://user-images.githubusercontent.com/12373088/45878893-477f2a00-bdd5-11e8-8013-d626dc3d3305.png)
