### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 751811032** [HeadingMobile/fabu.love#27]
npm start
Cannot find module 'C:\Users\rain\Desktop\fabu.love-master\server\node_modules\_bcrypt@3.0.1@bcrypt\lib\binding\bcrypt_lib.node'

可以说一下数据库的详细配置吗

**Comment by zakiso** [comment]
你用的什么系统啊?

**Comment by 751811032** [comment]
windows系统， 已经搞定了，谢谢，这个要依赖的东西多了，要添加python。
