### ISSUE TITLE
pm2

### ISSUE THREAD

**Issue by Shidou** [HeadingMobile/fabu.love#29]

**Comment by Shidou** [comment]
pm2如何部署该项目？

**Comment by zakiso** [comment]
项目里有一个process.json文件 pm2 start process.json就可以了

**Comment by chaseleasy** [comment]
> `6|fabu | 2018 - 10 - 30 22: 21 +08:00: Process API POST /api/user/register... 6|fabu | 2018 - 10 - 30 22: 21 +08:00: node /alidata/www/LoveFabu/server/index.js: symbol lookup error: /alidata/www/LoveFabu/server/node_modules/_bcrypt@3.0.2@bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE `
> 注册一下就服务重启了

这个换版本 使用8.9 版本就可以解决了

**Comment by chaseleasy** [comment]
PM2 使用方法 
新建   server.js 
内容  require('child_process').exec(`babel-node index.js`);
PM2 命令  pm2 start server.js -i max -e error.log -o output.log --no-daemon --interpreter ./node_modules/.bin/babel-node
