### ISSUE TITLE
api查看应用installUrl不带域名

### ISSUE THREAD

**Issue by yangguangchao** [HeadingMobile/fabu.love#34]
上传应用的第一个版本1.2.0，installUrl如下图所示：
![_20181112151642](https://user-images.githubusercontent.com/31229140/48332280-3db7cb80-e68e-11e8-8a68-3f85e3ac6fd2.png)

上传应用新版本第二个版本，installUrl如下图所示：
![_20181112152102](https://user-images.githubusercontent.com/31229140/48332400-9b4c1800-e68e-11e8-9185-7751cd59958b.png)

两个url一个带域名，一个不带域名，这样如果通过api获得下载地址，用这个下载地址下载app就会有问题

**Comment by zakiso** [comment]
应该是你最开始配置不对, 然后上传了一个版本,后来你配置好了之后,又上传了一次, 已经存在数据库的数据是没有做修正的.你需要把老版本删掉重新传一下

**Comment by yangguangchao** [comment]
这个应该是bug，第一次上传没有存储域名，上传新的版本才会存储域名。我在https://fabu.love上也是这样，api地址https://fabu.love/api/app/mipan
