### ISSUE TITLE
一直卡在，正在上传中 100%

### ISSUE THREAD

**Issue by honjia** [HeadingMobile/fabu.love#35]
一直卡在，正在上传中 100%

**Comment by wowtrxqn** [comment]
卡着，然后过了会提示read ECONNRESET

**Comment by honjia** [comment]
> 卡着，然后过了会提示read ECONNRESET

真的卡了很久都没反应啊。

**Comment by wowtrxqn** [comment]
> > 卡着，然后过了会提示read ECONNRESET
> 
> 真的卡了很久都没反应啊。

我调式到在parseIpa里面 ipaMataData就直接进err了，，，，然后上传apk 直接抛UnKnown OS，不知道作者官网怎么可以的

**Comment by wowtrxqn** [comment]
我是用window server部署的，是有问题

**Comment by honjia** [comment]
> 我是用window server部署的，是有问题

我用的是centos7 + node9 + mongodb + NGINX

**Comment by zakiso** [comment]
@honjia 卡在100% 应该是服务挂掉了, 你看看控制台的日志. 
@wowtrxqn  windows server是不支持的噢, 你看看有已关闭的issue里面有提到.

**Comment by wowtrxqn** [comment]
> @honjia 卡在100% 应该是服务挂掉了, 你看看控制台的日志.
> @wowtrxqn windows server是不支持的噢, 你看看有已关闭的issue里面有提到.

嗯，已经正在移植到linux了，开始没注意，自己调式了半天才发现windows下不行

**Comment by honjia** [comment]
> > @honjia 卡在100% 应该是服务挂掉了, 你看看控制台的日志.
> > @wowtrxqn windows server是不支持的噢, 你看看有已关闭的issue里面有提到.
> 
> 嗯，已经正在移植到linux了，开始没注意，自己调式了半天才发现windows下不行



> @honjia 卡在100% 应该是服务挂掉了, 你看看控制台的日志.
> @wowtrxqn windows server是不支持的噢, 你看看有已关闭的issue里面有提到.

 日志没报错哦，日志文件在哪里呢？

**Comment by zakiso** [comment]
@honjia  你看看 pm2 logs 呢

**Comment by ztan9766** [comment]
> @honjia 你看看 pm2 logs 呢

我也是一样的情况，本地ubuntu能上传，到了服务器centos上就是apk正常ipa卡100%，过很久直接报timeout没什么错误

**Comment by zakiso** [comment]
已解决

**Comment by zhangtianming777** [comment]
怎么解决的呢，我现在是苹果的上传会卡住，之前还可以，现在突然就会卡在100%了
