### ISSUE TITLE
可以支持Windows环境吗？

### ISSUE THREAD

**Issue by FavorPan** [HeadingMobile/fabu.love#36]
可以支持Windows环境吗？

**Comment by FavorPan** [comment]
可以支持Windows环境吗？

**Comment by zakiso** [comment]
可以的.
这个 主要是解析Android用的 aapt工具,现在只集成了macOS和linux的, 在项目 `fabu.love/server/library/apkparser/` 下是apk的解析库, 把windows的Android sdk中的aapt工具集成过来,再判断一下系统是windows就用该工具,就可以了. 有时间的话,欢迎提交pr.
