### ISSUE TITLE
Api接口调用

### ISSUE THREAD

**Issue by wutq** [HeadingMobile/fabu.love#37]
API调用的时候提示token没有 但是调用的参数中没有token字段啊请问再哪里设置的

**Comment by zakiso** [comment]
header中添加 `Authorization:Bearer ${token}`

**Comment by wutq** [comment]
好的 已经解决了

**Comment by tainenko** [comment]
apikey如何使用？ 添加 Authorization:Bearer ${apikey} 無效

**Comment by wangko27** [comment]
> apikey如何使用？ 添加 Authorization:Bearer ${apikey} 無效
1 先点击自己头像生产apiToken
2 在请求头里面加上apikey
比如：
`
curl -X POST "http://127.0.0.1:9898/api/apps/5c761666f62e754a8611a510/upload" -H "accept: application/json" -H "content-type: multipart/form-data" -F "file=@Nexless-1.3.0-release-1902270050_legu_signed_zipalign.apk" -H "accept: application/json" -H "apikey: a03eb3a1a1e05d3ec14701016138335c"
`

**Comment by zakiso** [comment]
在header中添加` "apikey:${用户面板中的apiToken}"`
