### ISSUE TITLE
linux下部署上传apk报错

### ISSUE THREAD

**Issue by wowtrxqn** [HeadingMobile/fabu.love#38]
![apk](https://user-images.githubusercontent.com/24369118/49276011-1c414700-f4b8-11e8-8627-861f958bdfa2.png)

**Comment by wowtrxqn** [comment]
用的node 8.14.0

**Comment by wowtrxqn** [comment]
自己解决了，closed吧

**Comment by LuffyLee3282479** [comment]
> 
> 
> 自己解决了，closed吧

你是怎么解决的？我自己搭了不同的环境，发现一个环境可以正常上传，一个不行

**Comment by wowtrxqn** [comment]
> > 自己解决了，closed吧
> 
> 你是怎么解决的？我自己搭了不同的环境，发现一个环境可以正常上传，一个不行

后来测了没问题，不过现在部署https有问题

**Comment by LuffyLee3282479** [comment]
> 
> 
> > > 自己解决了，closed吧
> > 
> > 
> > 你是怎么解决的？我自己搭了不同的环境，发现一个环境可以正常上传，一个不行
> 
> 后来测了没问题，不过现在部署https有问题

我是直接upload到100%后，后台会报错。然后npm 服务就崩溃了。整个上传都失败了，服务还崩溃了。很奇怪，查了很久没查到是哪的问题

**Comment by zakiso** [comment]
fixed

**Comment by linyicong** [comment]
@LuffyLee0110 @zakiso 我也是这个情况，上传包后，后端server直接报错了，服务还崩溃了。你们有解决了吗
