### ISSUE TITLE
部署https，下载有问题，微信扫描二维码进入后网络错误

### ISSUE THREAD

**Issue by wowtrxqn** [HeadingMobile/fabu.love#39]
预览界面出来了，但是下载的时候显示失败-网络错误，用微信扫二维码显示 网络出错，轻触屏幕重新加载:-1202, server config.js里面的baseUrl已经设置成https://xx.xxx.xx了（配置的https证书无误）
然后直接用safria浏览器打开预览的那个地址，下载就弹出127.0.0.1,,是nginx配置的问题吗？

**Comment by wowtrxqn** [comment]
现在我部署好了https://app.shasteel.cn，但是微信扫描后显示 网络出错，轻触屏幕重新加载:-1202

**Comment by LuffyLee3282479** [comment]
> 
> 
> 预览界面出来了，但是下载的时候显示失败-网络错误，用微信扫二维码显示 网络出错，轻触屏幕重新加载:-1202, server config.js里面的baseUrl已经设置成[https://xx.xxx.xx了（配置的https证书无误）](https://xx.xxx.xx%E4%BA%86%EF%BC%88%E9%85%8D%E7%BD%AE%E7%9A%84https%E8%AF%81%E4%B9%A6%E6%97%A0%E8%AF%AF%EF%BC%89)
> 然后直接用safria浏览器打开预览的那个地址，下载就弹出127.0.0.1,,是nginx配置的问题吗？

下载弹出127.0.0.1的话，是你数据库中初始化plist文件的时候有问题。可能需要重新进行系统配置，或者你可以修改一下数据库记录

**Comment by wowtrxqn** [comment]
> > 预览界面出来了，但是下载的时候显示失败-网络错误，用微信扫二维码显示 网络出错，轻触屏幕重新加载:-1202, server config.js里面的baseUrl已经设置成[https://xx.xxx.xx了（配置的https证书无误）](https://xx.xxx.xx%E4%BA%86%EF%BC%88%E9%85%8D%E7%BD%AE%E7%9A%84https%E8%AF%81%E4%B9%A6%E6%97%A0%E8%AF%AF%EF%BC%89)
> > 然后直接用safria浏览器打开预览的那个地址，下载就弹出127.0.0.1,,是nginx配置的问题吗？
> 
> 下载弹出127.0.0.1的话，是你数据库中初始化plist文件的时候有问题。可能需要重新进行系统配置，或者你可以修改一下数据库记录

 其他我都搞完了，ipa也可以装了，但是安卓的下载完后装不了

**Comment by wowtrxqn** [comment]
> > 预览界面出来了，但是下载的时候显示失败-网络错误，用微信扫二维码显示 网络出错，轻触屏幕重新加载:-1202, server config.js里面的baseUrl已经设置成[https://xx.xxx.xx了（配置的https证书无误）](https://xx.xxx.xx%E4%BA%86%EF%BC%88%E9%85%8D%E7%BD%AE%E7%9A%84https%E8%AF%81%E4%B9%A6%E6%97%A0%E8%AF%AF%EF%BC%89)
> > 然后直接用safria浏览器打开预览的那个地址，下载就弹出127.0.0.1,,是nginx配置的问题吗？
> 
> 下载弹出127.0.0.1的话，是你数据库中初始化plist文件的时候有问题。可能需要重新进行系统配置，或者你可以修改一下数据库记录

现在就剩这个问题了
哥，我在你网站上测试了https://fabu.love/gm0ird 可以安装，
我自己的下载后打开不了https://app.shasteel.cn/cuxvhi

**Comment by zakiso** [comment]
如果所有都配置好了, 你把以这个应用删除掉, 重新上传一下就好了
