### ISSUE TITLE
设置版本灰度功能怎么使用? 

### ISSUE THREAD

**Issue by jie123108** [HeadingMobile/fabu.love#4]
我使用https://fabu.love/ 进行测试. 
上传了两个版本.  两个版本都已经上线了. 
设置其中一个为灰度版本, 限制ip访问, ip为我的外网ip. 但是没有作用. 网页链接上看到的总是比较大的版本. 请问此处的灰度版本应该如何测试? 如何理解.

**Comment by zakiso** [comment]
设置灰度版本 只是检查更新会做判断, 接口文档中的 checkupdate会判断
比如有1.0和2.0和3.0三个版本, 最新的是3.0版本, 3.0版本使用灰度发布,2.0使用正常发布. 在检查更新的时候,如果用户满足灰度条件就能检查到3.0的版本,否则就是检查到2.0版本的更新.

**Comment by zakiso** [comment]
后续我们会配套开源一个检查更新的android和iOS的sdk

**Comment by jie123108** [comment]
从界面上看,怎么看出哪个版本是正常发布, 哪个是灰度发布呢? 
我在 https://fabu.love/  上面测试, 使用checkupdate测试, 好像也没有生效. 我把最新版本设置为灰度发布.  ip白名单, 使用的我的外网ip. 但是获取到的还是另外一个版本的. 
同时我看了下代码.  checkupdate接口实现中, 好像并没有对ipList的判断呀?

**Comment by zakiso** [comment]
哇漏掉了,  我刚也检查了一下,确实没有检查灰度的代码被注释了. 有时间的时候修复一下. 
界面上的话 灰度发布的版本会有一个灰色的 小原点, 正常发布的有一个绿色的小原点.

**Comment by zakiso** [comment]
已经修复了
