### ISSUE TITLE
上传apk文件，卡在100%，同时后台报错

### ISSUE THREAD

**Issue by LuffyLee0110** [HeadingMobile/fabu.love#40]
搭建环境为RHEL 6.4 node v9.9.0+mongo 3.6
后台抛出的错误如下：
![2018-12-7 9-27-15](https://user-images.githubusercontent.com/5328627/49624296-db8f8380-fa0b-11e8-9f26-17367bd2e68d.png)

**Comment by LuffyLee0110** [comment]
有没有人遇到过这个呢？很奇怪

**Comment by zakiso** [comment]
fixed
