### ISSUE TITLE
repository harbor.qianfan123.com/base/hd_nginx not found: does not exist or no pull access

### ISSUE THREAD

**Issue by faxinter** [HeadingMobile/fabu.love#43]

**Comment by wfxphoebus** [comment]
docker build 提示错误

**Comment by benwk** [comment]
镜像被删了，参照着写个基于 node 镜像的 Dockerfile 还是很容易的。

**Comment by zakiso** [comment]
I will update the Dockerfile. Will be soon.

**Comment by benwk** [comment]
auth.js 里找回密码部分将新密码发送到了固定的收件箱，建议修改为 body.email，避免不必要的误会

**Comment by zakiso** [comment]
谢谢提醒已修改

**Comment by zakiso** [comment]
dockerfile已经更新了，注意node镜像不要使用alpine版本的就行，用带glibc的版本
