### ISSUE TITLE
上传ipa包报错EONENT，详情见截图

### ISSUE THREAD

**Issue by yangguangchao** [HeadingMobile/fabu.love#44]
![_20181221102743](https://user-images.githubusercontent.com/31229140/50321342-680d6c00-050b-11e9-8d7c-3a5c88b7bd44.png)

**Comment by yuyongpeng** [comment]
我也遇到了这个问题

**Comment by yuyongpeng** [comment]
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/10458265/52701482-471a4200-2fb5-11e9-8f25-58ff4dfcbe5c.png">

**Comment by yangguangchao** [comment]
@yuyongpeng 这位大哥的方法可以修复https://github.com/HeadingMobile/fabu.love/issues/52，大佬提交更新会修复这个bug的
