### ISSUE TITLE
安卓进行代码混淆的安装包，上传100%就卡住了

### ISSUE THREAD

**Issue by yangguangchao** [HeadingMobile/fabu.love#5]
进行了测试，安卓没有混淆代码的安装包可以正常上传发布，混淆过代码的不行，可以下载腾讯的安卓QQ进行测试，很容易复现

**Comment by zakiso** [comment]
发现这个问题了, 感谢反馈

**Comment by yangguangchao** [comment]
客气了，咱们的分发平台还是挺好用的。

**Comment by zakiso** [comment]
目前修复了,但是还是有一些问题,比如知乎的app解析不出来icon,但是在mac osx系统下是能解析的,目前检查是apkparser的aapt工具,在不同平台下解析的数据不一样,还没有找好用的aapt

**Comment by yangguangchao** [comment]
[test.txt](https://github.com/HeadingMobile/fabu.love/files/2322825/test.txt)
这是我们安卓开发的一个app，上传一直卡在100%，报错信息详情见附件

**Comment by yangguangchao** [comment]
[qicai_release_V1.1.3_21_20180817.zip](https://github.com/HeadingMobile/fabu.love/files/2322839/qicai_release_V1.1.3_21_20180817.zip)
这是安卓apk包

**Comment by implion** [comment]
谢谢你的反馈，这个bug现已解决，导致bug的原因是我们在从apk中获取图片时使用了adm-zip这个库，有人提了issue：https://github.com/cthackers/adm-zip/issues/164，不过adm-zip最新版还是有这个问题，现在我们已经换成unzipper

**Comment by yangguangchao** [comment]
谢谢，希望咱们的分发平台越做越好
