### ISSUE TITLE
大佬感谢开源

### ISSUE THREAD

**Issue by lokisama** [HeadingMobile/fabu.love#52]
顺便汇报个BUG，看很多人说ipa上传报错

Process API error...
{ Error: ENOENT: no such file or directory, rename 'xxxx.png' -> 'yyyy_i.png'
    at Object.fs.renameSync (fs.js:766:18)
    at extractIpaIcon (/root/git/LoveFabu/server/controllers/upload.js:263:18)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: 'xxxx.png',
  dest: 'yyyy.png' }

翻看upload.js  263行
 await fs.renameSync(tmpOut, path.join(iconRelatePath, iconSuffix))
修改成  
await fs.renameSync(tmpOut, path.join(uploadDir,iconRelatePath, iconSuffix))
即可解决问题，望测试修复

另：nginx配置文件中 upload的配置也建议优化
 location /upload/ {
      #该root目录为根目录下config.json文件里dir目录 上传的apk和ipa文件当作静态文件处理
       root /home/ubuntu/fabulove/upload;
       expires  30d;
  }

如上app访问url  https://xxx.com/upload/，
必须在/home/ubuntu/fabulove/upload下再ln -s 一个实际路径，
变成
/home/ubuntu/fabulove/upload/upload/
怪怪的，建议改成
root /home/ubuntu/fabulove/;

**Comment by yangguangchao** [comment]
我试了一下，按照你提供的方案进行了修复，上传ipa正常了

**Comment by yangguangchao** [comment]
@zakiso ipa上传的问题是不是可以更新一下

**Comment by zakiso** [comment]
谢谢提醒和反馈，稍后和docker文件一同更新

**Comment by zakiso** [comment]
452cae3609391eddc29657ebfd775330ca27c811  已更新
