### ISSUE TITLE
docker无法运行

### ISSUE THREAD

**Issue by zsinba** [HeadingMobile/fabu.love#56]
编译的docker无法运行.
连接mongod无法成功.

**Comment by zakiso** [comment]
贴一下报错信息

**Comment by eternally1013** [comment]
> 贴一下报错信息

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fabu@1.0.0~prestart: fabu@1.0.0
6 info lifecycle fabu@1.0.0~start: fabu@1.0.0
7 verbose lifecycle fabu@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle fabu@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle fabu@1.0.0~start: CWD: /opt/server
10 silly lifecycle fabu@1.0.0~start: Args: [ '-c', 'babel-node index.js' ]
11 info lifecycle fabu@1.0.0~start: Failed to exec start script
12 verbose stack Error: fabu@1.0.0 start: `babel-node index.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid fabu@1.0.0
14 verbose cwd /opt/server
15 verbose Linux 3.10.0-957.el7.x86_64
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v8.9.4
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error fabu@1.0.0 start: `babel-node index.js`
23 error spawn ENOENT
24 error Failed at the fabu@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

数据库提示连接成功，但是点击注册时候docker直接死掉，这是bug日志

**Comment by faxinter** [comment]
一样的问题

**Comment by faxinter** [comment]
楼主，docker 是不是没有安装mongod,需要自己安装

**Comment by faxinter** [comment]
[root@MiWiFi-R3P-srv fabu.love-master]# docker run -p 9898:9898 --network host fabu:latest

> fabu@1.0.0 start /opt/server
> babel-node index.js

process controller: app.js...
mongodb://localhost:27017/fabulove
{"updateMode":{"type":"string","require":true},"versionId":{"type":"string","description":"如果传入了versionId则表示设置某个版本的更新方式"}}
{"shortUrl":"string","installWithPwd":"boolean","installPwd":"string","autoPublish":"boolean"}
{"installUrl":"string","showOnDownloadPage":"boolean","changelog":"string","updateMode":{"type":"string"}}
{"updateMode":{"type":"string"},"ipType":{"type":"string"},"ipList":{"type":"string"},"downloadCountLimit":{"type":"number"}}
{"versionId":{"type":"string","require":true},"versionCode":{"type":"string","require":true},"release":{"type":"bool","require":true}}
{"strategy":{"type":"object","properties":{"updateMode":{"type":"string"},"ipType":{"type":"string"},"ipList":{"type":"string"},"downloadCountLimit":{"type":"number"}}},"version":{"type":"object","properties":{"versionId":{"type":"string","require":true},"versionCode":{"type":"string","require":true},"release":{"type":"bool","require":true}}}}
{"versionId":{"type":"string","require":true},"versionCode":{"type":"string","require":true},"release":{"type":"bool","require":true}}
[Function: AppRouter]
process controller: auth.js...
{"username":{"type":"string","required":true},"password":{"type":"string","required":true}}
{"username":{"type":"string","required":true},"password":{"type":"string","required":true},"email":{"type":"string","required":true}}
{"oldpwd":{"type":"string","require":true},"newpwd":{"type":"string","require":true}}
{"mobile":{"type":"string"},"qq":{"type":"string"},"company":{"type":"string"},"career":{"type":"string"}}
{"email":{"type":"string","required":true}}
[Function: AuthRouter]
process controller: message.js...
[Function: MessageRouter]
process controller: miniapp.js...
{"name":{"type":"string","require":true},"appId":{"type":"string","require":true,"description":"小程序的appid"},"appSecret":{"type":"string","require":true,"description":"小程序的appSecret"},"teamId":{"type":"string","require":true,"description":"团队id,表示创建到哪个团队下"}}
{"appId":{"type":"string","require":true,"description":"小程序的appid"},"scene":{"type":"string","require":false,"description":"场景参数列如authcode=xxxx&match=xxxx"},"page":{"type":"string","require":false,"description":"入口页面"},"remark":{"type":"string","require":true,"description":"备注信息"},"teamId":{"type":"string","require":true,"description":"团队id"}}
{"appId":{"type":"string","require":true,"description":"小程序的appid"},"codeId":{"type":"string","require":true,"description":"入口页面"}}
[Function: MiniAppRouter]
process controller: team.js...
{"name":{"type":"string","required":true},"icon":{"type":"string","required":false}}
{"memberId":{"type":"string","required":true},"role":{"type":"string","required":true,"description":"传入manager或者guest"}}
{"emailList":{"type":"array","items":{"type":"string"},"description":"邮箱列表","required":true},"role":{"type":"string","required":true,"description":"成员角色manager/guest"}}
{"name":{"type":"string","required":true}}
[Function: TeamRouter]
process controller: upload.js...
[Function: UploadRouter]
Thu, 11 Apr 2019 00:17:29 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at index.js:44:5
App is listening on 9898.
(node:26) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
数据库连接成功
(node:26) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Process API POST /api/user/register...
/usr/local/bin/node: symbol lookup error: /opt/server/node_modules/_bcrypt@3.0.5@bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fabu@1.0.0 start: `babel-node index.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fabu@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-11T00_17_54_411Z-debug.log
[root@MiWiFi-R3P-srv fabu.love-master]#

**Comment by WhoJave** [comment]
@faxinter @eternally1013 你们解决了么 我也遇到了

**Comment by ytzk507** [comment]
我也遇到了同样的问题，请问你们有没有解决？ @WhoJave  @faxinter @zakiso

**Comment by tsangwaikey** [comment]
> 我也遇到了同样的问题，请问你们有没有解决？ @WhoJave @faxinter @zakiso

**Comment by zakiso** [comment]
已修复，请根据最新readme文件说明进行测试
