### ISSUE TITLE
用docker启动，注册时报错

### ISSUE THREAD

**Issue by eternally1013** [HeadingMobile/fabu.love#57]
数据库提示连接成功，但是点击注册时候docker直接死掉，这是debug日志

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fabu@1.0.0~prestart: fabu@1.0.0
6 info lifecycle fabu@1.0.0~start: fabu@1.0.0
7 verbose lifecycle fabu@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle fabu@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle fabu@1.0.0~start: CWD: /opt/server
10 silly lifecycle fabu@1.0.0~start: Args: [ '-c', 'babel-node index.js' ]
11 info lifecycle fabu@1.0.0~start: Failed to exec start script
12 verbose stack Error: fabu@1.0.0 start: `babel-node index.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid fabu@1.0.0
14 verbose cwd /opt/server
15 verbose Linux 3.10.0-957.el7.x86_64
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v8.9.4
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error fabu@1.0.0 start: `babel-node index.js`
23 error spawn ENOENT
24 error Failed at the fabu@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by WhoJave** [comment]
解决了么 我用docker时也遇到了

**Comment by eternally1013** [comment]
> 解决了么我我用docker时也遇到了

没有解决，等作者回复

**Comment by zakiso** [comment]
已解决 ，请根据最新readme说明运行

**Comment by zakiso** [comment]
已解决 ，请根据最新readme说明运行
