### ISSUE TITLE
 /opt/server/node_modules/_bcrypt@3.0.6@bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87Isol

### ISSUE THREAD

**Issue by WhoJave** [HeadingMobile/fabu.love#60]
centos 7 使用docker方式跑起来，注册的时候报错
` /opt/server/node_modules/_bcrypt@3.0.6@bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87Isol`

**Comment by zakiso** [comment]
已更新，请按照readme 使用最新版本测试
