### ISSUE TITLE
  Build failed with errors.

### ISSUE THREAD

**Issue by tsangwaikey** [HeadingMobile/fabu.love#64]
Building server
Step 1/12 : FROM node:10.15.3
 ---> 64c810caf95a
Step 2/12 : RUN npm install -g babel-cli     && npm install -g cnpm --registry=https://registry.npm.taobao.org
 ---> Using cache
 ---> be848f9f71c6
Step 3/12 : RUN mkdir -p /opt/data /opt/server /opt/web /opt/logs /var/cache/nginx/client_temp
 ---> Using cache
 ---> c1e20bc933ec
Step 4/12 : WORKDIR /opt/client
 ---> Using cache
 ---> 759ac0796d6c
Step 5/12 : ADD client /opt/client
 ---> Using cache
 ---> a2874a07a76f
Step 6/12 : RUN cnpm install
 ---> Using cache
 ---> 9cd22f0ca0db
Step 7/12 : RUN npm run build
 ---> Running in 5ec748f7ac87

> app-publisher@1.0.0 build /opt/client
> node build/build.js

Hash: 489452285d9b5e369e46
Version: webpack 3.12.0
Time: 25699ms
                                              Asset       Size  Chunks                    Chunk Names
                static/js/3.d64badf3d6d1e280eeb2.js    22.5 kB       3  [emitted]         
                  static/img/bg_picture.07f3585.png     279 kB          [emitted]  [big]  
                  static/fonts/icomoon.d37bb3e.woff    12.9 kB          [emitted]         
                   static/fonts/icomoon.f0ddd02.eot      13 kB          [emitted]         
                   static/fonts/icomoon.aa27446.ttf    12.9 kB          [emitted]         
                     static/img/icomoon.754976f.svg    43.5 kB          [emitted]         
                   static/img/empty_app.576448a.png    15.6 kB          [emitted]         
               static/img/ic_mobilphone.0bb8e79.png     127 kB          [emitted]         
                         static/img/box.43c604b.png    19.9 kB          [emitted]         
                static/js/0.8b9db10eba034829d62d.js    1.61 kB       0  [emitted]         vendor-async
                static/js/1.9ccbee3f5983cb2114aa.js    25.8 kB    1, 8  [emitted]         
                static/js/2.596cebe6f2329203d471.js    39.6 kB       2  [emitted]         
             static/fonts/element-icons.6f0a763.ttf      11 kB          [emitted]         
                static/js/4.2ec3ed405f6c72e56cc4.js    11.5 kB       4  [emitted]         
                static/js/5.3193cce99343c4169899.js    14.7 kB       5  [emitted]         
                static/js/6.2f77f61d496a8f7dbfdc.js    12.3 kB       6  [emitted]         
                static/js/7.c6e625d37fa62526e7ce.js    4.67 kB       7  [emitted]         
                static/js/8.9b7d731ef3bf1bc53a16.js    10.8 kB       8  [emitted]         
                static/js/9.b7fcd0a7668ff920f91e.js  205 bytes       9  [emitted]         
           static/js/vendor.563f3792d9a8030bae16.js     868 kB      10  [emitted]  [big]  vendor
              static/js/app.784393e0f6d3168d6050.js    8.15 kB      11  [emitted]         app
         static/js/manifest.0ac94c2ed02821498f8e.js    1.63 kB      12  [emitted]         manifest
static/css/app.3dfd2904b9e89665f80a84555ab68696.css     253 kB      11  [emitted]  [big]  app
                                         index.html  765 bytes          [emitted]         

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetail.vue
Module not found: Error: Can't resolve '../../api/moudle/miniApi' in '/opt/client/src/components/miniApplication'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetail.vue 51:0-52
 @ ./src/components/miniApplication/miniAppDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppList.vue
Module not found: Error: Can't resolve '../../api/moudle/miniApi' in '/opt/client/src/components/miniApplication'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppList.vue 47:0-52
 @ ./src/components/miniApplication/miniAppList.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/qrCode.vue
Module not found: Error: Can't resolve '../../api/moudle/miniApi' in '/opt/client/src/components/miniApplication'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/qrCode.vue 37:0-52
 @ ./src/components/miniApplication/qrCode.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetail.vue
 @ ./src/components/miniApplication/miniAppDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetailHeader.vue
Module not found: Error: Can't resolve '../../api/moudle/miniApi' in '/opt/client/src/components/miniApplication'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetailHeader.vue 28:0-52
 @ ./src/components/miniApplication/miniAppDetailHeader.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetail.vue
 @ ./src/components/miniApplication/miniAppDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/auth/auth.vue
Module not found: Error: Can't resolve '../../common/js/utils' in '/opt/client/src/components/auth'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/auth/auth.vue 92:0-42
 @ ./src/components/auth/auth.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/personalInfo.vue
Module not found: Error: Can't resolve '../../common/js/utils' in '/opt/client/src/components/user'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/personalInfo.vue 23:0-42
 @ ./src/components/user/personalInfo.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/userInfo.vue
 @ ./src/components/user/userInfo.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/editorVersion.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/appDetail'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/editorVersion.vue 54:0-48
 @ ./src/components/appDetail/editorVersion.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appVersions.vue
 @ ./src/components/appDetail/appVersions.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetail.vue
 @ ./src/components/appDetail/appDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appVersions.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/appDetail'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appVersions.vue 118:0-48
 @ ./src/components/appDetail/appVersions.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetail.vue
 @ ./src/components/appDetail/appDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appSetting.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/appDetail'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appSetting.vue 29:0-48
 @ ./src/components/appDetail/appSetting.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetail.vue
 @ ./src/components/appDetail/appDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/graySetting.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/appDetail'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/graySetting.vue 62:0-48
 @ ./src/components/appDetail/graySetting.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appVersions.vue
 @ ./src/components/appDetail/appVersions.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetail.vue
 @ ./src/components/appDetail/appDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetail.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/appDetail'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetail.vue 28:0-48
 @ ./src/components/appDetail/appDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetailHeader.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/appDetail'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetailHeader.vue 41:0-48
 @ ./src/components/appDetail/appDetailHeader.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appDetail/appDetail.vue
 @ ./src/components/appDetail/appDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appList/appList.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/appList'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/appList/appList.vue 53:0-48
 @ ./src/components/appList/appList.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/auth/auth.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/auth'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/auth/auth.vue 91:0-49
 @ ./src/components/auth/auth.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/main/headerNav.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/main'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/main/headerNav.vue 55:0-106
 @ ./src/components/main/headerNav.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/main/main.vue
 @ ./src/components/main/main.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetail.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/miniApplication'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetail.vue 52:0-48
 @ ./src/components/miniApplication/miniAppDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppList.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/miniApplication'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppList.vue 49:0-48
 @ ./src/components/miniApplication/miniAppList.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetailHeader.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/miniApplication'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetailHeader.vue 29:0-48
 @ ./src/components/miniApplication/miniAppDetailHeader.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/miniApplication/miniAppDetail.vue
 @ ./src/components/miniApplication/miniAppDetail.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/team/teamMgr.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/team'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/team/teamMgr.vue 85:0-44
 @ ./src/components/team/teamMgr.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/team/teamItem.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/team'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/team/teamItem.vue 21:0-44
 @ ./src/components/team/teamItem.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/team/teamMgr.vue
 @ ./src/components/team/teamMgr.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/changePassword.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/user'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/changePassword.vue 25:0-51
 @ ./src/components/user/changePassword.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/userInfo.vue
 @ ./src/components/user/userInfo.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/userMessage.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/user'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/userMessage.vue 42:0-48
 @ ./src/components/user/userMessage.vue
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/main/main.vue
 @ ./src/components/main/main.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/userInfo.vue
Module not found: Error: Can't resolve '../../mgr/userMgr' in '/opt/client/src/components/user'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/user/userInfo.vue 40:0-62
 @ ./src/components/user/userInfo.vue
 @ ./src/router/index.js
 @ ./src/main.js

ERROR in ./src/api/basehttp.js
Module not found: Error: Can't resolve '../mgr/userMgr' in '/opt/client/src/api'
 @ ./src/api/basehttp.js 5:0-48
 @ ./src/main.js

ERROR in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Can't resolve './mgr/userMgr' in '/opt/client/src'
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 9:0-44
 @ ./src/App.vue
 @ ./src/main.js

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-publisher@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-publisher@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-20T08_27_35_133Z-debug.log
ERROR: Service 'server' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1

**Comment by WhoJave** [comment]
你这系统啥版本的 我的centos7 上是ok的

**Comment by tsangwaikey** [comment]
> 你这系统啥版本的 我的centos7 上是ok的

mac os 10.14.4

**Comment by zakiso** [comment]
@tsangwaikey  我是10.14.2 是OK的， 你docker和docker-compose版本是最新的吗？

**Comment by tsangwaikey** [comment]
Docker version 18.09.2
docker-compose version 1.23.2

**Comment by zakiso** [comment]
你本地已经运行了mongodb了， 把本地的关了，端口被本地占用了，docker容器没法导出这个端口了。
你可以把 docker-compose.yml下面这一段注释掉
```
ports:
      - "27017:27017"
```

或者你不使用docker-compose.直接用docker单独启动服务也可以
