### ISSUE TITLE
本地-DOCKER部署-注册无响应

### ISSUE THREAD

**Issue by ytzk507** [HeadingMobile/fabu.love#66]
MAC，DOCKER部署，注册时一直在转，没有其他响应。请问LOG应该如何去看？

**Comment by zakiso** [comment]
日志查看 `docker logs 容器ID`
如果没响应是数据库没连上

**Comment by ytzk507** [comment]
的确是数据库没连上。大概是使用docker来运行mongodb,关于mongodb的配置数据需要修改？

**Comment by zakiso** [comment]
本地没有运行mongodb的话无需修改，如果有运行的话，把`docker-compose.yml`中port里面的27017都去掉，
