### ISSUE TITLE
DOCKER部署无法连接数据库

### ISSUE THREAD

**Issue by ytzk507** [HeadingMobile/fabu.love#68]
Mongoose connection disconnected
Mongoose connection error: connect ECONNREFUSED 172.19.0.2:27017

MAC正面
本机通过brew安装的mongodb已经卸载，但是依然是这个日志，导致注册无响应。谢谢

**Comment by zakiso** [comment]
这个问题我也遇到过， 在有些机器正常有些机器不正常，非常奇怪。目前怀疑的原因是mongo的容器还没完全启动好，这个时候就去尝试链接了，然后报错了。

**Comment by ytzk507** [comment]
呵呵，尴尬。现在是找不到mongoose.js这个文件。是因为版本的原因这个文件取消掉了还是怎么？因为我对NODE相关内容不太了解，所以现在变成伸手党了。

**Comment by zakiso** [comment]
我刚提交了一下

**Comment by ytzk507** [comment]
Mongoose connection disconnected
Mongoose connection error: connect ECONNREFUSED 172.19.0.2:27017
Process API POST /api/user/register...
 ~/ArcOpenSource/fabu.love/docker   hotfix 

-------------
基于hotfix分支，仍然存在同样的问题。

**Comment by zakiso** [comment]
启动后稍等一会 1分钟什么的 也不行吗？

**Comment by ytzk507** [comment]
不行。

**Comment by ytzk507** [comment]
我换个干净的centos安装试试。如果实在不行就只能先放弃了

**Comment by zakiso** [comment]
好的 我也很疑惑，等有时间的时候我再查找一下原因。 不过如果不行的话，你可以单独启动app服务的容器，然后数据库连你本地的。或者不使用docker部署

**Comment by ytzk507** [comment]
我找运维同事做了部署，是成功的。大概是我对DOCKER和NODE都不了解的原因吧。这个issue可以关掉了。
