### ISSUE TITLE
点击预览后显示currentVersionCode is not defined

### ISSUE THREAD

**Issue by xttanwei** [HeadingMobile/fabu.love#7]
我上传了apk，并且已经发布了，但是进入预览页面，仍然显示currentVersionCode is not defined

我在你们的demo页面也是一样的
![image](https://user-images.githubusercontent.com/4161489/44502618-e6284600-a6c4-11e8-8673-aff7f0dc8eb5.png)
![image](https://user-images.githubusercontent.com/4161489/44502628-ed4f5400-a6c4-11e8-8f1c-a982aa85d5c8.png)

**Comment by xttanwei** [comment]
我检查了代码
在/server/controllers/app.js:439:48，使用了不存在的变量currentVersionCode
我检查了下逻辑，这里不需要这个~
我修改成
if (!version || !version.versionCode)
可以了

**Comment by zakiso** [comment]
谢谢反馈,稍后修复

**Comment by zakiso** [comment]
已修复
