### ISSUE TITLE
上传的安卓包下载不了，服务端报错

### ISSUE THREAD

**Issue by cyg056** [HeadingMobile/fabu.love#71]
![image](https://user-images.githubusercontent.com/19517553/56728290-04c76b00-6785-11e9-9c69-cdf345ce3d12.png)

**Comment by zakiso** [comment]
能否提供一下重现步骤和apk包呢？

**Comment by cyg056** [comment]
1.环境是centos 7.6，node 10.15.3
2.部署是client端报错，固修改了部分包依赖的版本
![image](https://user-images.githubusercontent.com/19517553/56849165-aab0dc00-6923-11e9-983c-7e50d49a748d.png)
3.上传了apk包，并发布了（包是在斗鱼的网页上下载了一个斗鱼的APK包做测试）
4.通过预览打开下载页面
5.手机扫描下载的二维码下载，服务端报错

**Comment by zakiso** [comment]
已修复
