### ISSUE TITLE
centos7下DOCKER构建报错

### ISSUE THREAD

**Issue by ytzk507** [HeadingMobile/fabu.love#73]
[root@xxx docker]# docker-compose up -d --build
Building server
Step 1/12 : FROM node:10.15.3
10.15.3: Pulling from library/node
e79bb959ec00: Extracting [======================================>            ]  34.87MB/45.34MBBete
========> ]  10.73MB/10.78MBete
d54db43011fd: Downloading [=========================================69d473365bb3: Downloading [==========>                              6e2490ee2dc8: Downloading
6381e1b5feaa: Waiting
b1efb42c63e2: Waiting
ERROR: Service 'server' failed to build: unauthorized: authentication required

**Comment by ytzk507** [comment]
有什么需要验证的吗。。。。。

**Comment by zakiso** [comment]
没有。  是你的docker-hub配置有问题，或者你自己的代理设置有问题。建议google一下。docker pull的时候失败了，检查自己的网络配置是否有代理。是否要登录docker-hub等
