### ISSUE TITLE
上传app后，点击预览，不管安卓还是苹果，都显示未检测到版本信息

### ISSUE THREAD

**Issue by xingye311** [HeadingMobile/fabu.love#77]
上传app后，点击预览，不管安卓还是苹果，都显示未检测到版本信息，不止是我本地跑的是这样，上传到https://fabu.apppills.com后，点击预览，也显示的是未检测到版本信息

**Comment by zakiso** [comment]
需要发布一下，上传成功后，版本列表里面右侧有个飞机的按钮，点击发布版本，就能检测到了

**Comment by xingye311** [comment]
噢，可以了，不清楚流程，汗...谢谢啦
