### ISSUE TITLE
能不能支持持久化的 API Key

### ISSUE THREAD

**Issue by solrex** [HeadingMobile/fabu.love#8]
每次都用用户名和密码获取 token 有些麻烦，要是有持久化的 API Key 就好了。

**Comment by zakiso** [comment]
在什么场景下需要用持久化的API key呢?

**Comment by solrex** [comment]
@zakiso 用脚本自动化 CI 发布时，记录密码每次都要获取新的 token 比较麻烦且危险。

**Comment by zakiso** [comment]
好的 , 可以支持

**Comment by zakiso** [comment]
#17 已经加上该功能

**Comment by fldroid** [comment]
请问这个持久化API key我要怎么传给服务器校验
直接Bearer xxx会报jwt malformed错

**Comment by AgoniNemo** [comment]
@fldroid 我也遇到这个的问题了 也是报错`jwt malformed` 请问你解决了吗？

**Comment by zakiso** [comment]
header中的字段名称叫 “ apikey”

在header中传入 
`apikey:xxxxxxxxxx`

**Comment by AgoniNemo** [comment]
`curl -X POST "http://192.168.0.253:9898/api/apps/xxxxx/upload" -H "accept: application/json" -H "apikey: Bearer xxxxx" -H "content -type: mudata" -F "file=@/Users/mac/Documents/App.ipa"`  这样写有问题吗？现在报错`Internal Server Error` @zakiso

**Comment by zakiso** [comment]
不需要 Bearer

**Comment by AgoniNemo** [comment]
谢谢  可以了 @zakiso
