### ISSUE TITLE
docker-compose up -d --build

### ISSUE THREAD

**Issue by AgoniNemo** [HeadingMobile/fabu.love#82]
Docker version 18.09.6, build 481bc77156
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

使用`docker-compose up -d --build`命令编译

错误信息
`ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.`

试过：
`
sudo usermod -a -G docker $USER
`

**Comment by zakiso** [comment]
docker-compose 版本需要升级一下 试试

**Comment by AgoniNemo** [comment]
更新版本：docker-compose version 1.24.1, build 4667896 可用
但是上传包完成  在预览的时候   提示未检测到版本信息
