### ISSUE TITLE
docker部署完成后，在本地访问http://localhost:9898/login,注册和登录接口一直无响应，其他的api都是ok的

### ISSUE THREAD

**Issue by hk1554075856** [HeadingMobile/fabu.love#83]
![WechatIMG247](https://user-images.githubusercontent.com/12810952/60873122-6a95a000-a268-11e9-9eef-4bfa1d7c79bc.png)

**Comment by hk1554075856** [comment]
这个是mongonDB的log
![image](https://user-images.githubusercontent.com/12810952/60875909-7172e180-a26d-11e9-909a-76ed2bed5061.png)

**Comment by zakiso** [comment]
应该是数据库链接没成功，你再检查下数据库链接是不是正常的 试试

**Comment by hk1554075856** [comment]
今天早上重新启动，显示mongo is up-to-date,已经OK了，谢谢！
