### ISSUE TITLE
上传卡进度条或到100%不动

### ISSUE THREAD

**Issue by wangmeng17** [headingmobile/fabu.love#92]
用docker分开部署前后端，使用https，上传到某一阶段或者到100%就卡住不动，日志如下
![image](https://user-images.githubusercontent.com/22473197/68367317-7179e400-0170-11ea-95b5-d1883c0314b8.png)

**Comment by itstudying** [comment]
![image](https://user-images.githubusercontent.com/35722827/68916398-c1742e80-07a0-11ea-89eb-b1a152f7374d.png)

设置下上传目录应该就行

**Comment by linyicong** [comment]
@wangmeng17 这个问题解决了吗？我有配置上传目录的，但是还是报错了

**Comment by wangmeng17** [comment]
> @wangmeng17 这个问题解决了吗？我有配置上传目录的，但是还是报错了

解决了，开始后端应用部署在一个容器中，nginx和前用应用部署在另一个应用中，这样就会出现上述问题。然后我将前后端应用部署在同一个容器中，nginx在另一个容器中就没问题了。

**Comment by linyicong** [comment]
我是直接在机器上部署的。那就不知道问题出在哪里了...

**Comment by linyicong** [comment]
你的容器是什么系统，什么版本的？我看到有人说要glibc升级到2.17就可以了

**Comment by linyicong** [comment]
我好像只用了后端server端 和nginx。那个client的前端应用也要运行的吗？

**Comment by wangmeng17** [comment]
@linyicong 是的

**Comment by linyicong** [comment]
谢谢。我的解决了。前端的我是npm编译好了就交给nginx了。就是只有server端nginx。
这个项目需要glibc2.14版本的才行，上传ipa包才包这个版本要求。上传apk只是报代码错误。

**Comment by zhangtianming777** [comment]
怎么解决的呢，我现在是苹果的上传会卡住，之前还可以，现在突然就会卡在100%了
